### ISSUE TITLE
plugin: requires CGO_ENABLED=1

### ISSUE THREAD

**Issue by ColetteContreras** [v2ray/ext#19]
https://github.com/golang/go/issues/19569

https://github.com/v2ray/ext/blob/d4617913e5a5856aeb13166df05161129d028dfc/bazel/build.bzl#L27

**Comment by ColetteContreras** [comment]
#20

**Comment by VictoriaRaymond** [comment]
Does this mean existing plugin mode not working at all? As you are trying to re-compile, you can directly include your plugin [here](https://github.com/v2ray/v2ray-core/blob/master/main/distro/all/all.go), and not necessary to use plugin mode. If that's the case, I'd like to remove the plugin mode completely.

**Comment by ColetteContreras** [comment]
I think that Golang plugin mode is not a prod feature, there are several conditions to run a plugin, such as:
- it requires `CGO_ENABLED=1`
- plugin.Open: plugin was built with a different version of package X

i would be happy if you remove plugin mode, it's useless, i have been suffered with that during the whole implementation.

Thanks for your suggest, i'll go through with it.
