### ISSUE TITLE
关于Docker在ARM64设备上运行出错

### ISSUE THREAD

**Issue by caicy1991** [v2ray/ext#26]
设备为ARM64的，在Docker Hub库里面找到v2ray/official后直接pull镜像到本地设备，然后运行时提示
`standard_init_linux.go:207: exec user process caused "exec format error"`
不知是何原因，貌似是跨平台的问题好像。可否解决一下，谢谢大佬

**Comment by kslr** [comment]
https://github.com/v2ray/v2ray-core/releases/download/v4.18.0/v2ray-linux-arm64.zip
建议你直接运行程序，还能节省点性能
